# Copyright 1999-2023. Plesk International GmbH.
project_name: plesk
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - ''
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}mac
      {{- else if eq .Os "windows" }}win
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  filters:
    exclude:
      - '^TECH'
